### ISSUE TITLE
[Question]: Change the instance_name variable to machine_name?

### ISSUE THREAD

**Issue by muhmah-motahari** [devopshobbies/terraform-tutorial#20]
### Describe and write the question.

Wouldn't it be better to change the ```instance_name``` variable to ```machine_name```?
In ```variables.tf``` file defined ```machine_name``` and that's value is defined in ```terraform.tfvars```
but in ```module/ec2/variables.tf``` and ```module/ec2/main.tf``` defined ```instance_name```

**Comment by babakDoraniArab** [comment]
@muhmah-motahari hey buddy, yea it can be a good idea. you can make you changes and create a pull request for it . 


cheers
