### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by mosyiran** [devopshobbies/terraform-tutorial#21]
hello Please explain what is difference between variables.tf and variable.tf in modules/ec2 folder? We must writing variables in both file?what is difference between provider.tf and provider.tf in modules/ec2 folder? What is reason for creating module folder? When we create and need modules folder? What is situation we must writing modules folder? Thanks 

@babakDoraniArab

**Comment by mehdi-ra** [comment]
Hi :hand:
- **When we create and need modules folder? What is situation we must writing modules folder?**
A module is a collection of Terraform resources that can be reused across multiple projects or environments.
For example, let's say you have a web application that you're deploying to multiple AWS regions. Each region requires the same set of resources, but with different configuration values. In this case, you could create a module that defines the common set of resources, and then use that module in each of your regional Terraform configurations. This is not the only use-case of modules and you might find it helpful when your project is getting more complex and your services are running on different configurations or services of AWS.

- **Please explain what is difference between variables.tf and variable.tf in modules/ec2 folder?**
The `variables.tf` holds global project variables but `variable.tf` holds the variables of the module.

- **We must write variables in both file?**
No, There is no need to define everything in both files. The `variables.tf` contains variables shared across all the modules but the `variable.tf` contains module scoped variables and are not accessible outside the module.

- **what is difference between provider.tf and provider.tf in modules/ec2 folder?**
The `providers.tf` and `provider.tf` files are as same as the `variables.tf` and the `variable.tf`. The providers defined in root will be shared across the entire modules. 

Have a good time.

**Comment by mosyiran** [comment]
Thanks very much
